source 'https://rubygems.org'

gem "jekyll", "~> 4.3.2"

# gem "just-the-docs"        # always download the latest release
gem "just-the-docs", "0.5.4" # pinned to the current release
gem 'jekyll-relative-links'
